# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    registries:
      - npmjs-org
      - tiptap-pro
    schedule:
      interval: "weekly"
    groups:
      tiptap:
        patterns:
          - "@tiptap/*"
        update-types:
          - "minor"
          - "patch"
registries:
  npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org/
  tiptap-pro:
    type: npm-registry
    url: https://registry.tiptap.dev/
    token: ${{ secrets.TIPTAP_PRO_TOKEN }}
